# Generated by Django 3.1.5 on 2021-01-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210104_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='user_images', verbose_name='Фото пользователя'),
        ),
    ]
