# Generated by Django 3.1.5 on 2021-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210110_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Полный пакет', 'full'), ('Бесплатный пакет', 'free')], default='Бесплатный пакет', max_length=30),
        ),
    ]
