# Generated by Django 3.1.4 on 2021-01-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
    ]
