# Generated by Django 3.1.4 on 2021-01-13 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0002_link_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.CharField(max_length=200, verbose_name='Длинная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=30, unique=True, verbose_name='Сокращенная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
